//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyGamingBASIC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Providers
    {
        public Game_Providers()
        {
            this.Game = new HashSet<Game>();
        }
    
        public int intProviderID { get; set; }
        public string strProviderName { get; set; }
    
        public virtual ICollection<Game> Game { get; set; }
    }
}
