//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyGamingBASIC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Members
    {
        public int intGameMemberID { get; set; }
        public int intGameID { get; set; }
        public int intMemberID { get; set; }
        public bool bitOwnGame { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Members Members { get; set; }
    }
}
