//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyGamingBASIC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members
    {
        public Members()
        {
            this.Game_Members = new HashSet<Game_Members>();
        }
    
        public int intMemberID { get; set; }
        public string strFirstName { get; set; }
        public string strLastName { get; set; }
        public string strSteamAccount { get; set; }
        public string strBlizzardAccount { get; set; }
        public string strEAAccount { get; set; }
        public string strThreeDSFriendCode { get; set; }
        public string strMinecraftAccount { get; set; }
        public string strLeagueOfLegendsAccount { get; set; }
    
        public virtual ICollection<Game_Members> Game_Members { get; set; }
    }
}
